version: "3"

services:
  eureka-server:
    image: eureka-server:latest
    ports:
      - "8002:8002"
    network_mode: "host"

  zuul-api-gateway:
    image: zuul-api-gateway:latest
    ports:
      - "8003:8003"
    network_mode: "host"

  hystrix-dashboard:
    image: hystrix-dashboard:latest
    ports:
      - "8001:8001"
    network_mode: "host"

  zipkin-server:
    image: zipkin-server:latest
    ports:
      - "9411:9411"
    network_mode: "host"

  acme-service:
    image: acme-service:latest
    ports:
      - "8010:8010"
    network_mode: "host"