server:
  port: 8002

security:
  basic:
    enabled: true
  user:
      name: admin
      password: admin

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance:
      hostname: localhost
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8002/eureka/