server:
  port: 8010

spring:
  application:
      name: acme-service
  sleuth:
    sampler:
      percentage: 0.2

#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG

eureka:
  client:
    instance:
      statusPageUrlPath: /info
      healthCheckUrlPath: /health
      hostname: localhost
      preferIpAddress: true
    serviceUrl:
      defaultZone:  http://admin:admin@127.0.0.1:8002/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

