server:
  port: 8010

spring:
  application:
      name: acme-service
  sleuth:
    sampler:
      percentage: 1

#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG

#EUREKA CONFIG is HANDLED NOW by the config-server
#eureka:
#  client:
#    instance:
#      statusPageUrlPath: /info
#      healthCheckUrlPath: /health
#      hostname: localhost
#      preferIpAddress: true
#    serviceUrl:
#      defaultZone:  http://admin:admin@127.0.0.1:8002/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

swagger:
  title: ACME Service REST API
  description: At this level, you're at the point at which something is at its best or most highly developed
  version: @project.version@
  termsOfServiceUrl: https://www.apache.org/licenses/LICENSE-2.0
  license: Apache License 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Akram Tabka
    url: https://tabka.net
    email: tabkram@gmail.com

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs