server:
  port: 9411

spring:
  application:
      name: zipkin-server

eureka:
    client:
       instance:
          hostname: localhost
          preferIpAddress: true
       serviceUrl:
          defaultZone:  http://admin:admin@127.0.0.1:8002/eureka/
