server:
  port: 8009

spring:
  application:
      name: swagger-service

#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG

eureka:
  client:
    instance:
      statusPageUrlPath: /info
      healthCheckUrlPath: /health
      hostname: localhost
      preferIpAddress: true
    serviceUrl:
      defaultZone:  http://admin:admin@127.0.0.1:8002/eureka/